samples/messenger/urls.py
from django.urls import path

from django.views.generic import RedirectView

from . import views

app_name = 'messenger'

urlpatterns = [
    path('', views.websiteHomePage, name='welcome'),

    path('login/', views.homePage, name='home'),

    path('update-avatar/', views.updateUserAvatar, name='update-avatar'),
    
    path('deactivate-account/', views.deactivateUserAccount, name='deactivate-account'),

    path('save-venue-image/', views.saveVenueImage, name='write-venue-image'),

    path('delete-venue-image/', views.deleteVenueImage, name='delete-venue-image'),

    path('fetch-venue-images/', views.findVenueImages, name='get-venue-images'),

    path('reset/', views.getResetCodeViaEmail, name='start-reset'),

    path('submit-reset-code/', views.displayResetPage, name='collect-reset-code'),

    path('reset-password/', views.resetUserPassword, name='password-reset'),

    path('search-by-district/', views.viewServicesByDistrict, name='search-by-district'),

    path('signup/', views.registerPage, name='register'),

    path('about-us/', views.aboutPage, name='about'),

    path('venues/', views.venuePage, name='venue'),

    path('venue-detail/<str:venueName>/', views.viewVenueDetails, name='venue-details'),
    
    path('fetch-venue-edit-details/', views.extractVenueEditDetails, name='venue-edit-details'),

    path('chat/', views.chatPage, name='chat-page'),

    path('blog-editor/', views.blogEditorPage, name='blog-editor'),

    path('blog-page/<int:pageId>', views.viewBlogPostDetails, name='blog-post'),

    path('delete-post/<int:postCategoryId>/', views.deleteSpecificPostCategory, name='delete-post'),

    path('delete-post-data/<int:postItemId>/', views.deleteSpecificPostItem, name='delete-post-data'),

    path('email/', views.emailPage, name='email-page'),

    path('submit-message/<int:userGroup>/', views.submitChatMessage, name='chat-upload'),

    path('gallery/', views.galleryPage, name='gallery'),

    path('gallery-manager/', views.galleryControlPanel, name='gallery-control'),

    path('update-image-state/', views.updateGalleryImageState, name='gallery-image-control'),

    path('page-registry/', views.viewPageRegistry, name='page-registry'),

    path('services/', views.servicesPageView, name='restaurant'),

    path('services/<str:serviceCategory>/', views.viewServicesByCategory, name='services-by-category'),

    path('blog/', views.blogPostPage, name='blog'),

    path('submit-comment/', views.submitPostComment, name='submit-comment'),

    path('get-post-data/', views.getPostInformation, name='get-post-data'),

    path('contact/', views.contactPage, name='contact'),

    path('book-mariahill-gardens/', views.bookMariahillGardens, name='book-gardens'),

    path('record-booking/', views.recordBookingInformation, name='record-booking'),

    path('logout/', views.logoutUser, name='logout-user'),

    path('uploads/', views.fileManagerPage, name='file-manager'),

    path('alter-primary-credentials/', views.managePrimaryCredentials, name='primary-credentials'),

    path('user-access/', views.manageNextOfKins, name='next-of-kins'),
    
    # bookings
    path('booking-requests/', views.manageBookingRequests, name='booking-requests'),

    path('register-admin/', views.registerNewAdmin, name='register-admin'),

    path('wipe-admin-user/<int:adminId>', views.ripOffAdmin, name='wipe-administrator'),

    path('get-admin-profile/', views.fetchAdminDetail, name='get-admin-data'),

    path('alter-admin-profile/', views.changeAdminPermissions, name='alter-admin-profile'),

    path('alter-local-user-credentials/', views.updateUserCredentials, name='update-local-user-credentials'),

    path('grant-admin-access/<int:idOfAdmin>/', views.giveSecondaryAdminAccess, name='grant-admin-access'),

    path('delete-upload/<int:imageId>/', views.deleteSpecificUpload, name='wipe-upload'),

    path('delete-thread/', views.wipeMessagesThread, name='wipe-thread'),

    path('delete-service/<int:serviceId>/', views.deleteSpecificService, name='wipe-service'),

    path('delete-page-category/<int:categoryId>/', views.deletePageCategory, name='wipe-page-category'),

    path('delete-venue/<int:venueId>/', views.deleteSpecificVenue, name='wipe-venue'),

    path('delete-contact/<int:contactId>/<int:whoseContact>/', views.deleteSpecificContact, name='wipe-contact'),

    path('delete-comments/<int:postId>/', views.deletePostComments, name='delete-comments'),

    path('delete-reply/<int:replyId>/', views.deleteSpecificReply, name='wipe-reply'),

    path('delete-vendor-page/<int:pageId>/', views.deleteVendorPage, name='wipe-vendor-page'),

    path('delete-all-chats/<str:userName>/', views.deleteChatsForGivenUser, name='wipe-all-chats'),

    path('delete-testimonial/<int:testimonialId>/', views.deleteSpecificTestimonial, name='wipe-testimonial'),

    path('editor/<int:sectionId>/', views.makeWebsiteEdit, name='edit-website'),

    path('update-venue/', views.updateVenueFeaturedStatus, name='update-venue'),

    path('update-post-state/', views.updatePostFeaturedState, name='update-post'),

    path('get-user-chats/', views.getNewUserChats, name='get-chats'),

    path('submit-message/', views.submitSimpleMessage, name='submit-message'),

    path('submit-page-category/', views.registerPageCategory, name='submit-page-category'),

    path('get-thread/', views.getMessageThreadData, name='get-thread'),

    path('submit-reply/', views.submitAdminReply, name='send-reply'),

    path('save-page/', views.recordNewVendorPage, name='save-page'),

    path('save-form-detail/', views.recordBookingFormDetail, name='booking-form-detail'),

    path('get-page-data/', views.fetchPageMeta, name='get-page-meta'),

    path('page-manager/<int:pageId>', views.manageThirdPartyPage, name='manage-vendor-page'),

    path('save-page-details/', views.savePageDetails, name='save-page-details'),

    path('save-page-handles/', views.savePageHandles, name='save-page-handles'),

    path('save-page-services/', views.savePageServices, name='save-page-services'),

    path('delete-page-service/<int:serviceId>', views.wipePageService, name='wipe-page-service'),

    path('get-service-meta/', views.fetchServiceInformation, name='get-service-info'),

    path("service-providers/<str:vendorPageName>/", views.viewVendorPage, name='vendor-page'),

]

samples/samples/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("messenger.urls")),
    path("accounts/", include("userenv.urls")),
    path("control/", include("mariadmin.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

samples/mariasite/models.py
from django.db import models

# Create your models here.

samples/mariasite/views.py
from django.shortcuts import render

# Create your views here.

samples/mariasite/templates/mariasite/sections/banner-section.html
{% load static %}

<!-- banner -->
<section class="hero-wrap"
  {% if banner_image is None %}

    style="background-image: url({% static 'mariasite/color/site-core/theme/unwind/images/bg_1.jpg' %})"
  {% else %}
    style="background-image: url({{ banner_image }})"

  {% endif %}
    >
    <div class="overlay"></div>
    <div class="container">
      <div class="row no-gutters slider-text align-items-center justify-content-center">
        <div class="col-lg-10 text-center">
          <div style="margin-bottom:4rem !important;">
            <h2 class="maria-header">Mariahill Gardens And Events Services</h2>
            <span class="banner-sub-title mt-3">"A one stop center for all your event needs"</span>
          </div>

        </div>
      </div>
    </div>
</section>

samples/mariasite/templates/mariasite/sections/blog-section.html
{% load static %}

<section class="ftco-section bg-light">
    <div class="container-xl">
      <div class="row justify-content-center mb-5">
        <div class="col-md-7 heading-section text-center" data-aos="fade-up" data-aos-duration="1000">
          <span class="subheading">Our Blog</span>
          <h2>Recent Posts</h2>
        </div>
      </div>

      <div class="row">
        {% for eachPost in featured_posts %}
          <div class="col-md-6 col-lg-3 d-flex">
            <div class="blog-entry justify-content-end" data-aos="fade-up" data-aos-duration="1000" data-aos-delay="100">
              <a href="{% url 'messenger:blog-post' eachPost.id %}" class="block-20 img d-flex align-items-end" style="background-image: url({{ eachPost.heading_image }})">
              </a>

              <div class="text">
                
                <p class="meta">
                  <span>Admin</span> <span>{{ eachPost.date }}</span>
                  <a href="{% url 'messenger:blog-post' eachPost.id %}">{{ eachPost.comment_count }} Comments</a>
                </p>

                <h3 class="heading mb-3">
                  <a href="{% url 'messenger:blog-post' eachPost.id %}">{{ eachPost.heading }}</a>
                </h3>

                <p>
                  {{ eachPost.body_preview }}
                </p>

              </div>
            </div>
          </div>

        {% empty %}

          <div class="d-flex justify-content-center align-items-center">
            <p class="lead">No Posts Yet</p>
          </div>
          
        {% endfor %}

      </div>
    </div>
</section>

samples/mariasite/templates/mariasite/sections/contact-section.html
<section class="ftco-section bg-light">
    <div class="container">
        <div class="row no-gutters justify-content-center">
            <div class="col-md-12">
                <div class="wrapper">
                    <div class="row g-0">
                        <div class="col-lg-6">
                            <div class="contact-wrap w-100 p-md-5 p-4">
                                <h3>Contact us</h3>
                                <p class="mb-4">We're open for any suggestion or just to have a chat</p>
                            
                                <div class="row mb-4">
                                    {% if events_contacts.location %}
                                        <div class="col-md-6">
                                            <div class="dbox w-100 d-flex align-items-start">
                                                <div class="text">
                                                    <p><span>Address:</span> {{ events_contacts.location }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}

                                    {% if events_contacts.telephone %}
                                        <div class="col-md-6">
                                            <div class="dbox w-100 d-flex align-items-start">
                                                <div class="text">
                                                    <p><span>Phone:</span> {{ events_contacts.telephone }}</p>
                                                </div>
                                            </div>
                                        </div>
                                    {% endif %}
                                </div>

                                <form id="contactForm" action="{% url 'messenger:submit-message' %}" method="post" class="contactForm">
                                    {% csrf_token %}
                                    <div class="row">

                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <input type="text" class="form-control" name="user-name" placeholder="Name" required>
                                            </div>
                                        </div>

                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <input type="email" class="form-control" name="user-email" id="email" placeholder="Email" required>
                                            </div>
                                        </div>

                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <input type="text" class="form-control" name="message-subject" id="subject" placeholder="Subject" required>
                                            </div>
                                        </div>

                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <textarea name="actual-message" class="form-control" id="message" cols="30" rows="4" placeholder="Create a message here" required></textarea>
                                            </div>
                                        </div>

                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <input type="submit" value="Send Message" class="btn btn-primary">
                                                
                                                {% if messages %}
                                                    <div class="submitting">
                                                        {% for eachMessage in messages %}
                                                            <span>{{ eachMessage }}</span>

                                                        {% endfor %}
                                                    </div>
                                                {% endif %}
                                            </div>
                                        </div>
                                    </div>
                                </form>

                                <div class="w-100 social-media mt-5">
                                <h3>Follow us here</h3>
                                    <p>
                                        {% if events_contacts.twitter %}
                                            <a href="{{ contacts.twitter }}"><span class="fa fa-twitter" style="font-size: 12px;"></span></a>
                                        {% endif %}

                                        {% if events_contacts.facebook %}
                                            <a href="{{ contacts.facebook }}"><span class="fa fa-facebook" style="font-size: 12px;"></span></a>
                                        {% endif %}

                                        {% if events_contacts.instagram %}
                                            <a href="{{ contacts.instagram }}"><span class="fa fa-instagram" style="font-size: 12px;"></span></a>
                                        {% endif %}

                                        {% if events_contacts.whatsapp %}
                                            <a href="{{ contacts.whatsapp }}"><span class="fa fa-whatsapp" style="font-size: 12px;"></span></a>
                                        {% endif %}
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-6 d-flex align-items-stretch">
                        <div id="map" class="bg-white">
                                <iframe style="height:100%;width:100%;border:0;" frameborder="0" src="https://www.google.com/maps/embed/v1/place?q=Entebbe+Road,+Kampala,+Uganda&key=AIzaSyBFw0Qbyq9zTFTd-tUY6dZWTgaQzuU17R8"></iframe>
                            </div>
                        </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

samples/mariasite/templates/mariasite/sections/featured-venues.html
{% load static %}

<section class="ftco-section bg-light">
    <div class="container-xl">
        <div class="row justify-content-center">
            <div class="col-md-8 heading-section text-center mb-5" data-aos="fade-up" data-aos-duration="1000">
                <span class="subheading">Other Venues</span>
                <h2 class="mb-4 w-100">Venues From Our Partners</h2>
            </div>
        </div>

        {% if featured_list %}
            <div class="row justify-content-center">
              <div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
                <div class="carousel-indicators">
                  <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
                  <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
                  <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
                </div>
                <div class="carousel-inner">
                  {% for eachVenue in featured_list %}
                    {% if forloop.counter == 1 %}
                      <div class="carousel-item active" style="display: flex !important; align-items:center !important;">
                        <a href="{% url 'messenger:venue-details' eachVenue.name  %}" class="d-block w-100">
                          <img src="{{ eachVenue.image }}" class="d-block w-100 img-fluid" alt="...">
                          <div class="d-block" style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">
                            <span style="color: white;" class="venue-name-featured">{{ eachVenue.name }}</span>
                            <p style="color: white;" class="venue-description">
                              <q>
                                {{ eachVenue.description.capitalize }}
                              </q>
                            </p>
                          </div>
                        </a>
                      </div>

                    {% else %}

                      <div class="carousel-item">
                        <a href="{% url 'messenger:venue-details' eachVenue.name  %}" class="d-block w-100">
                        <img src="{{ eachVenue.image }}" class="d-block w-100 img-fluid" alt="...">
                        <div class="d-block" style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">
                          <span style="color: white;" class="venue-name-featured">{{ eachVenue.name }}</span>
                          <p style="color: white;" class="venue-description"><q>{{ eachVenue.description.capitalize }}</q></p>

                        </div>
                        </a>
                      </div>

                    {% endif %}

                  {% endfor %}
                </div>

                <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
                  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Previous</span>
                </button>
                <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
                  <span class="carousel-control-next-icon" aria-hidden="true"></span>
                  <span class="visually-hidden">Next</span>
                </button>
              </div>
            </div>

        {% else %}
            <div class="col-12 d-flex w-100 justify-content-center">
                <p> No Featured Venues Yet</p>
            </div>


        {% endif %}
    </div>
</section>

samples/mariasite/templates/mariasite/sections/footer-section.html
{% load static %}

<footer class="ftco-footer">
    <div class="container-xl">
      <div class="row mb-5 pb-5 gx-5">
        <div class="col-md-4">
          <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2 logo d-flex">
              <a class="navbar-brand align-items-center" href="#">
                <span class>Mariahill <small> Gardens, Entebbe</small></span>
              </a>
            </h2>
            <p>
              Discover the Ideal Setting for Your Special Day & Let you Celebrate in Style at Our Enchanting Gardens
            </p>
            <ul class="ftco-footer-social list-unstyled mt-2">
              {% if contacts.twitter %}
                <li>
                  <a href="{{ contacts.twitter }}"><span class="fa fa-twitter"></span></a>
                </li>
              {% endif %}

              {% if contacts.facebook %}
                <li>
                  <a href="{{ contacts.facebook }}"><span class="fa fa-facebook"></span></a>
                </li>
              {% endif %}

              {% if contacts.instagram %}
                <li>
                  <a href="{{ contacts.instagram }}"><span class="fa fa-instagram"></span></a>
                </li>
              {% endif %}

              {% if contacts.whatsapp %}
                <li>
                  <a href="{{ contacts.whatsapp }}"><span class="fa fa-whatsapp"></span></a>
                </li>
              {% endif %}
            </ul>
          </div>
        </div>
        <div class="col-md-4">
          <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2">Quick Links</h2>
            <ul class="list-unstyled">
              <li>
                <a href="{% url 'messenger:welcome' %}"
                  ><span class="fa fa-chevron-right me-2"></span>Home</a
                >
              </li>
              <li>
                <a href="{% url 'messenger:about' %}"
                  ><span class="fa fa-chevron-right me-2"></span>About</a
                >
              </li>
              <li>
                <a href="{% url 'messenger:venue' %}"
                  ><span class="fa fa-chevron-right me-2"></span>Bookings</a
                >
              </li>
              <li>
                <a href="{% url 'messenger:gallery' %}">
                  <span class="fa fa-chevron-right me-2"></span>
                  Gallery
                </a>
              </li>
              <li>
                <a href="{% url 'messenger:blog' %}">
                  <span class="fa fa-chevron-right me-2"></span>
                  Blog
                </a>
              </li>
            </ul>
          </div>
        </div>

        <div class="col-md-4">
          <div class="ftco-footer-widget mb-4">
            <h2 class="ftco-heading-2">Have a Questions?</h2>
            <div class="block-23 mb-3">
              <ul>
                {% if contacts.location %}
                  <li>
                    <div>
                      <span class="icon fa fa-map marker"></span>
                      <span class="text">
                        <span>{{ contacts.location }}</span>
                      </span>
                    </div>
                  </li>
                {% endif %}

                {% if contacts.telephone %}
                  <li>
                    <div>
                      <span class="icon fa fa-phone"></span>
                      <span class="text">
                        <span>{{ contacts.telephone }}</span>
                      </span>
                    </div>
                  </li>
                {% endif %}
                
                {% if contacts.email %}
                  <li>
                    <div>
                      <span class="icon fa fa-paper-plane pr-4"></span>
                      <span class="text">
                        <span>{{ contacts.email }}</span>
                      </span>
                    </div>
                  </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="container-fluid px-0 py-5 bg-darken">
      <div class="container-xl">
        <div class="row">
          <div class="col-md-12 text-center">
            <p
              class="mb-0"
              style="color: rgba(255, 255, 255, 0.5); font-size: 13px"
            >
              Copyright &copy;
              <script>
                document.write(new Date().getFullYear());
              </script>
              All rights reserved |
              <a
                href="{% url 'messenger:welcome' %}"
                >Maria Hill Gardens</a
              >
            </p>
          </div>
        </div>
      </div>
    </div>
</footer>

samples/mariasite/templates/mariasite/sections/gallery-dynamic.html
{% extends "mariasite/core/base.html" %}

{% load static %}

{%  block page_main %}
    {% include 'mariasite/headers/secondary-header.html' %}

    {% include 'mariasite/sections/gallery-loader.html' %}


{% endblock %}

samples/mariasite/templates/mariasite/sections/post-details.html
{% load static %}

<div class="site-cover site-cover-sm same-height overlay single-page" style="background-image: url({{ post_details.heading_image }});">
  <div class="container">
    <div class="row same-height justify-content-center">
      <div class="col-md-6">
        <div class="post-entry text-center">
          <h1 class="mb-4">
            {{ post_details.heading }}
          </h1>
          <div class="post-meta align-items-center text-center">
            <figure class="author-figure mb-0 me-3 d-inline-block">
              <img src="{% static 'mariadmin/local-update/frest/admin/assets/img/avatars/general.png' %}" alt="Image" class="img-fluid">
            </figure>
            <span class="d-inline-block mt-1">
              Admin
            </span>
            <span>&nbsp;-&nbsp; {{ post_details.date }} </span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<section class="section">
  <div class="container">

    <div class="row blog-entries element-animate">

      <div class="col-md-12 col-lg-8 main-content">

        <div class="post-content-body">
          <p>
            {{ post_details.top_body }}
          </p>
          <div class="row my-4">
            <div class="col-md-12 mb-4">
              <img src="{{ post_details.main_image }}" alt="Image placeholder" class="img-fluid rounded">
            </div>

            {% if post_details.left_image %}
              <div class="col-md-6 mb-4">
                <img src="{{ post_details.left_image }}" alt="Image placeholder" class="img-fluid rounded">
              </div>
            {% endif %}

            {% if post_details.right_image %}
              <div class="col-md-6 mb-4">
                <img src="{{ post_details.right_image }}" alt="Image placeholder" class="img-fluid rounded">
              </div>
            {% endif %}

          </div>

          <p>
            {{ post_details.lower_body }}
          </p>
        </div>


        <div class="pt-5">
          <p>
            Categories:  
            {% if post_details.is_list is True %}

              {% for eachCategory in post_details.categories %}

                <a href="#">{{ eachCategory }}</a>,

              {% endfor %}

            {% else %}

              <a href="#">{{ post_details.categories }}</a>,

            {% endif %}
          </p>
        </div>


        <div class="pt-5 comment-wrap">
          <h3 class="mb-5 heading">
            {{ comments_count }} Comment (s)

          </h3>
          <ul class="comment-list">
            {% for eachComment in comments %}
              <li class="comment">
                <div class="comment-body">

                  <h3>{{ eachComment.name }}</h3>

                  <div class="meta">
                    {{ eachComment.date }}
                  </div>

                  <p>
                    {{ eachComment.comment }}
                  </p>

                </div>
              </li>

            {% empty %}
              <p class="lead">
                No Comments Yet!
              </p>

            {% endfor %}

          </ul>
          <!-- END comment-list -->

          <div class="comment-form-wrap pt-5">
            <h3 class="mb-5">Leave a comment</h3>
            <form action="{% url 'messenger:submit-comment' %}" method="post" class="p-5 bg-light">

              {% csrf_token %}

              <div class="form-group">
                <label for="poster-name">Name *</label>
                <input type="text" name="poster-name" class="form-control" id="poster-name" required>
              </div>

              <div class="form-group">
                <input type="hidden" name="post-id" value="{{ post_id }}">
              </div>


              <div class="form-group">
                <label for="poster-comment">Message</label>
                <textarea name="poster-comment" id="poster-comment" cols="30" rows="10" class="form-control" required></textarea>
              </div>

              <div class="form-group">
                <input type="submit" value="Post Comment" class="btn btn-primary">
              </div>

            </form>
          </div>
        </div>

      </div>

      <!-- END main-content -->

      <div class="col-md-12 col-lg-4 sidebar">
        {% include 'mariasite/sections/post-side-box.html' %}

      </div>
      <!-- END sidebar -->

    </div>
  </div>
</section>


<!-- Start posts-entry -->
<section class="section posts-entry posts-entry-sm bg-light">
  <div class="container">
    <div class="row mb-4">
      <div class="col-12 text-uppercase text-black">More Blog Posts</div>
    </div>
    <div class="row">
      {% for eachOtherPost in footer_posts %}

        <div class="col-md-6 col-lg-3">
          <div class="blog-entry">
            <a href="{% url 'messenger:blog-post' eachOtherPost.id %}" class="img-link">

              <img src="{{ eachOtherPost.heading_image }}" alt="Image" class="img-fluid">

            </a>
            <span class="date">{{ eachOtherPost.date }}</span>

            <h2>
              <a href="{% url 'messenger:blog-post' eachOtherPost.id %}">
                {{ eachOtherPost.heading }}
              </a>
            </h2>

            <p>
              {{ eachOtherPost.body_preview }}
            </p>

            <p>
              <a href="{% url 'messenger:blog-post' eachOtherPost.id %}" class="read-more">Continue Reading</a>
            </p>
          </div>
        </div>

      {% empty %}

        <div class="d-flex justify-content-center p-5">
          <p class="lead">There are no other posts!</p>
        </div>

      {% endfor %}
    </div>
  </div>
</section>
<!-- End posts-entry -->

samples/mariasite/templates/mariasite/sections/post-side-box.html
<div class="sidebar-box">
    <h3 class="heading">Popular Posts</h3>
    <div class="post-entry-sidebar">
      <ul>
        {% for eachPopularPost in featured_posts %}

          <li>
            <a href="{% url 'messenger:blog-post' eachPopularPost.id %}">
              <img src="{{ eachPopularPost.image }}" alt="Image placeholder" class="me-4 rounded">
              
              <div class="text">
                <h4>{{ eachPopularPost.heading }}</h4>

                <div class="post-meta">
                  <span class="mr-2">{{ eachPopularPost.date }}</span>
                </div>
              </div>
            </a>
          </li>

        {% empty %}

          <li>
            <p class="lead">No Posts yet!</p>
          </li>

        {% endfor %}
      </ul>
    </div>
  </div>
  <!-- END sidebar-box -->