samples/mariadmin/urls.py
from django.urls import path

from . import views

app_name = 'admin_panel'


urlpatterns = [
    path("", view=views.adminHomePage, name='admin-home'),
    path('addcategory/', views.registerCategory, name='insert-category'),
    path('deletecategory/<int:categoryId>', views.deleteCategory, name='delete-category'),
]

samples/messenger/urls.py
from django.urls import path

from django.views.generic import RedirectView

from . import views

app_name = 'messenger'

urlpatterns = [
    path('', views.websiteHomePage, name='welcome'),

    path('login/', views.homePage, name='home'),

    path('update-avatar/', views.updateUserAvatar, name='update-avatar'),
    
    path('deactivate-account/', views.deactivateUserAccount, name='deactivate-account'),

    path('save-venue-image/', views.saveVenueImage, name='write-venue-image'),

    path('delete-venue-image/', views.deleteVenueImage, name='delete-venue-image'),

    path('fetch-venue-images/', views.findVenueImages, name='get-venue-images'),

    path('reset/', views.getResetCodeViaEmail, name='start-reset'),

    path('submit-reset-code/', views.displayResetPage, name='collect-reset-code'),

    path('reset-password/', views.resetUserPassword, name='password-reset'),

    path('search-by-district/', views.viewServicesByDistrict, name='search-by-district'),

    path('signup/', views.registerPage, name='register'),

    path('about-us/', views.aboutPage, name='about'),

    path('venues/', views.venuePage, name='venue'),

    path('venue-detail/<str:venueName>/', views.viewVenueDetails, name='venue-details'),
    
    path('fetch-venue-edit-details/', views.extractVenueEditDetails, name='venue-edit-details'),

    path('chat/', views.chatPage, name='chat-page'),

    path('blog-editor/', views.blogEditorPage, name='blog-editor'),

    path('blog-page/<int:pageId>', views.viewBlogPostDetails, name='blog-post'),

    path('delete-post/<int:postCategoryId>/', views.deleteSpecificPostCategory, name='delete-post'),

    path('delete-post-data/<int:postItemId>/', views.deleteSpecificPostItem, name='delete-post-data'),

    path('email/', views.emailPage, name='email-page'),

    path('submit-message/<int:userGroup>/', views.submitChatMessage, name='chat-upload'),

    path('gallery/', views.galleryPage, name='gallery'),

    path('gallery-manager/', views.galleryControlPanel, name='gallery-control'),

    path('update-image-state/', views.updateGalleryImageState, name='gallery-image-control'),

    path('page-registry/', views.viewPageRegistry, name='page-registry'),

    path('services/', views.servicesPageView, name='restaurant'),

    path('services/<str:serviceCategory>/', views.viewServicesByCategory, name='services-by-category'),

    path('blog/', views.blogPostPage, name='blog'),

    path('submit-comment/', views.submitPostComment, name='submit-comment'),

    path('get-post-data/', views.getPostInformation, name='get-post-data'),

    path('contact/', views.contactPage, name='contact'),

    path('book-mariahill-gardens/', views.bookMariahillGardens, name='book-gardens'),

    path('record-booking/', views.recordBookingInformation, name='record-booking'),

    path('logout/', views.logoutUser, name='logout-user'),

    path('uploads/', views.fileManagerPage, name='file-manager'),

    path('alter-primary-credentials/', views.managePrimaryCredentials, name='primary-credentials'),

    path('user-access/', views.manageNextOfKins, name='next-of-kins'),
    
    # bookings
    path('booking-requests/', views.manageBookingRequests, name='booking-requests'),

    path('register-admin/', views.registerNewAdmin, name='register-admin'),

    path('wipe-admin-user/<int:adminId>', views.ripOffAdmin, name='wipe-administrator'),

    path('get-admin-profile/', views.fetchAdminDetail, name='get-admin-data'),

    path('alter-admin-profile/', views.changeAdminPermissions, name='alter-admin-profile'),

    path('alter-local-user-credentials/', views.updateUserCredentials, name='update-local-user-credentials'),

    path('grant-admin-access/<int:idOfAdmin>/', views.giveSecondaryAdminAccess, name='grant-admin-access'),

    path('delete-upload/<int:imageId>/', views.deleteSpecificUpload, name='wipe-upload'),

    path('delete-thread/', views.wipeMessagesThread, name='wipe-thread'),

    path('delete-service/<int:serviceId>/', views.deleteSpecificService, name='wipe-service'),

    path('delete-page-category/<int:categoryId>/', views.deletePageCategory, name='wipe-page-category'),

    path('delete-venue/<int:venueId>/', views.deleteSpecificVenue, name='wipe-venue'),

    path('delete-contact/<int:contactId>/<int:whoseContact>/', views.deleteSpecificContact, name='wipe-contact'),

    path('delete-comments/<int:postId>/', views.deletePostComments, name='delete-comments'),

    path('delete-reply/<int:replyId>/', views.deleteSpecificReply, name='wipe-reply'),

    path('delete-vendor-page/<int:pageId>/', views.deleteVendorPage, name='wipe-vendor-page'),

    path('delete-all-chats/<str:userName>/', views.deleteChatsForGivenUser, name='wipe-all-chats'),

    path('delete-testimonial/<int:testimonialId>/', views.deleteSpecificTestimonial, name='wipe-testimonial'),

    path('editor/<int:sectionId>/', views.makeWebsiteEdit, name='edit-website'),

    path('update-venue/', views.updateVenueFeaturedStatus, name='update-venue'),

    path('update-post-state/', views.updatePostFeaturedState, name='update-post'),

    path('get-user-chats/', views.getNewUserChats, name='get-chats'),

    path('submit-message/', views.submitSimpleMessage, name='submit-message'),

    path('submit-page-category/', views.registerPageCategory, name='submit-page-category'),

    path('get-thread/', views.getMessageThreadData, name='get-thread'),

    path('submit-reply/', views.submitAdminReply, name='send-reply'),

    path('save-page/', views.recordNewVendorPage, name='save-page'),

    path('save-form-detail/', views.recordBookingFormDetail, name='booking-form-detail'),

    path('get-page-data/', views.fetchPageMeta, name='get-page-meta'),

    path('page-manager/<int:pageId>', views.manageThirdPartyPage, name='manage-vendor-page'),

    path('save-page-details/', views.savePageDetails, name='save-page-details'),

    path('save-page-handles/', views.savePageHandles, name='save-page-handles'),

    path('save-page-services/', views.savePageServices, name='save-page-services'),

    path('delete-page-service/<int:serviceId>', views.wipePageService, name='wipe-page-service'),

    path('get-service-meta/', views.fetchServiceInformation, name='get-service-info'),

    path("service-providers/<str:vendorPageName>/", views.viewVendorPage, name='vendor-page'),

]

samples/samples/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("messenger.urls")),
    path("accounts/", include("userenv.urls")),
    path("control/", include("mariadmin.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

samples/mariadmin/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth.decorators import login_required

from django.views.decorators.cache import cache_control

from django.http import JsonResponse

from django.contrib import messages

from django.http import HttpRequest

from .models import (Category, 
                    AboutHeading, AboutDetails, LeftCard, 
                    RightCard, OfferedService, MiddleGrid, 
                    VenueItem, Testimonial, StatisticsMeta, 
                    Contacts, WebsiteHeadingImage, EventsServicesContacts, 
                    gardensTourVideoLink, BookingFormDetail
                    )

from messenger.views import ControlUtils



def getAdminHomeContext():
    # get available categories
    availableCategories = [
            {
                'category': str(eachCategory),
                'tag': eachCategory.pk
            } for eachCategory in Category.objects.all()
        ]
    
    # get the banner image
    bannerImage = WebsiteHeadingImage.objects.all().first()
    
    videoLinkUrl = gardensTourVideoLink.objects.all().first()
    
    # get the booking form object
    bookingFormObject = BookingFormDetail.objects.all().first()
    
    bookingFormText, bookingFormImage = bookingFormObject.formText, bookingFormObject.imageUrl
    
    adminContext = {
        "contact_form_text": bookingFormText,
        "form_side_image":  bookingFormImage,
        'tour_video_link': videoLinkUrl.videoUrl if videoLinkUrl else None,
        'categories': availableCategories,
        'banner_image': bannerImage.imageUrl if bannerImage else None,
        'heading': str(AboutHeading.objects.all().first()) if AboutHeading.objects.all().first() else None,
        'about_detail': str(AboutDetails.objects.all().first()) if AboutDetails.objects.all().first() else None,
        'left_card_data': {'heading': LeftCard.objects.all().first().leftCardHeading, 'text': LeftCard.objects.all().first().leftCardText, 'image': LeftCard.objects.all().first().leftCardImageUrl} if LeftCard.objects.all().first() else None,
        'right_card_data': {'heading': RightCard.objects.all().first().rightCardHeading, 'text': RightCard.objects.all().first().rightCardText, 'image': RightCard.objects.all().first().rightCardImageUrl} if RightCard.objects.all().first() else None,
        'uploads': ControlUtils().getUploadsData(),
        # 
        'services': [
            {'name': eachService.serviceName, 'details': eachService.serviceDetails, 'id':eachService.pk} for eachService in OfferedService.objects.all()],
        'ribbon': {
            'heading': MiddleGrid.objects.all().first().gridTitle,
            'message': MiddleGrid.objects.all().first().gridMessage,
            'text': MiddleGrid.objects.all().first().gridButtonText,
            'url': MiddleGrid.objects.all().first().gridRedirectionUrl
            },
        'venues': [
                {
                    'name': eachVenue.venueName,
                    'capacity': eachVenue.venueCapacity,
                    'description': eachVenue.venueDescription.capitalize(),
                    'featured': eachVenue.isFeatured,
                    'id': eachVenue.pk
                } for eachVenue in VenueItem.objects.all()
            ],
        'testimonials': [
                {
                    'name': eachTestimonial.guestName,
                    'comment': eachTestimonial.guestComment,
                    'position': eachTestimonial.guestPosition,
                    'image': eachTestimonial.guestImageUrl,
                    'id': eachTestimonial.pk
                } for eachTestimonial in Testimonial.objects.all()
            ],
        'statistics': {
                'guests': StatisticsMeta.objects.all().first().happyGuests,
                'events': StatisticsMeta.objects.all().first().hostedEvents,
                'staff': StatisticsMeta.objects.all().first().staffCount,
                'venues': StatisticsMeta.objects.all().first().venueCount
            
            },
        'contacts': [
                {
                    'type': eachContact.contactType.capitalize(),
                    'value': eachContact.contactValue,
                    'id': eachContact.pk,
                    'kind': 1
                } for eachContact in Contacts.objects.all()
            ],
        'events_contacts': [
                {
                    'type': eachContact.contactType.capitalize(),
                    'value': eachContact.contactValue,
                    'id': eachContact.pk,
                    'kind': 2
                } for eachContact in EventsServicesContacts.objects.all()
            ]
        
        }


    return adminContext

def determinePageRoute(accessTag):
    # 'website': True,
    # 'blog': True,
    # 'pages': True,
    # 'comms': True,
    # 'users': True
    if accessTag == 'blog':
        redirectObject = redirect("messenger:blog-editor")
        
    elif accessTag == 'pages':
        redirectObject = redirect("messenger:page-registry")
        
    elif accessTag == 'comms':
        redirectObject = redirect("messenger:chat-page")
        
    else:
        redirectObject = redirect("messenger:next-of-kins")
        
    return redirectObject

def getFirstPermission(request:HttpRequest):
    # get first permission
    for eachPermission, permissionValue in request.session['allowed_pages'].items():
        if permissionValue is True:
            firstPermission = eachPermission
            break
        

    return firstPermission
    
    
        
    

@login_required(login_url='messenger:home')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def adminHomePage(request):
    # determine if its the home page to be displayed
    if request.session['allowed_pages']['website'] is True:
        # load
        adminContext = getAdminHomeContext()
        
        return render(request, "mariadmin/index.html", context=adminContext)
    
    else:
        # determine redirection route
        firstPermission = getFirstPermission(request=request)
        
        # get a route
        responseObject = determinePageRoute(accessTag=firstPermission)
        
        return responseObject


    
    
    



@login_required(login_url='messenger:home')
def registerCategory(request):
    if request.method == "POST":
        # get the submitted data
        submittedData = request.POST.dict()
        
        # get the category name
        reportedCategoryName  = submittedData['category-name'].lower().capitalize()
        
        isItDuplicate = Category.objects.filter(modelName=reportedCategoryName).first()
        
        if isItDuplicate:
            # alert error
            messages.warning(request, "Category Name exists already!")
        
        else:
            # create the new category
            newCategory = Category.objects.create(modelName=reportedCategoryName)
            
            # save the new category
            newCategory.save()
            
            # alert success
            messages.success(request, "Category name was registered!")
            
        return redirect("admin_panel:admin-home")
    
    else:
        # print("Here")
        
        return JsonResponse(
            dict(
                message = 'resource not accessible'
            )
        )
        
@login_required(login_url='messenger:home')
def deleteCategory(request, categoryId):
    # get and delete the object
    categoryToDelete = get_object_or_404(Category, pk=categoryId)
    
    # delete the category
    categoryToDelete.delete()
    
    return redirect("admin_panel:admin-home")

samples/mariadmin/templates/mariadmin/sections/about-meta.html
<div class="row w-100">
    <section id="about-meta">
        <div class="card mb-4 mx-2">
            <h5 class="card-header"><i class="fa-regular fa-address-card me-2"></i>About Information</h5>
            <div class="card-body demo-vertical-spacing demo-only-element">
                <div class="mb-4">
                    <form action="{% url 'messenger:edit-website' 1 %}" method="post">
                        {% csrf_token %}
                        <label for="about-heading" class="form-label">About Section Ribbon</label>
                        <div class="input-group">
                            <input type="text" name="about-heading" class="form-control" id="about-heading" placeholder="We are Maria Hill Gardens" required>
                            <button class="btn btn-outline-primary" type="submit">
                                <i class="fa-solid fa-circle-plus me-2"></i>Save
                            </button>
        
                        </div>
                    </form>

                    <div class="form-text">
                        {{ heading }}
                    </div>
                </div>


                <div class="mb-4">
                    <form action="{% url 'messenger:edit-website' 17 %}" method="post">
                        {% csrf_token %}
                        <label for="about-image-holder" class="form-label">About Ribbon Image</label>
                        <div class="input-group">
                            <input type="text" name="about-image-url" class="form-control" id="about-image-holder" placeholder="Select and Image" required>
                            <button class="btn btn-outline-primary image-selectors" type="button" data-output-receiver="about-image-holder">
                                <i class="fa-solid fa-file-image me-2"></i> Choose Image
                            </button>

                            <button class="btn btn-outline-primary" type="submit">
                                <i class="fa-solid fa-circle-plus me-2"></i></i> Save
                            </button>
                        </div>
                    </form>

                    <div class="form-text">
                        {% if not about_image_url is None %}
                            {{ about_image_url }}
                        {% else %}
                        This image appears on the left of the about quotation

                        {% endif %}
                    </div>
                </div>
    
                <form action="{% url 'messenger:edit-website' 2 %}" method="post">
                    {% csrf_token %}
                    <div class="input-group">
                        <span class="input-group-text">New About</span>
                        <textarea class="form-control" name="about-details" placeholder="Detailed information about Mariahill Gardens"></textarea>
                        <button class="btn btn-outline-primary" type="submit">
                            <i class="fa-solid fa-circle-plus me-2"></i></i> Save
                        </button>
                    </div>
                </form>

    
                <div class="form-group">
                    <label class="form-label lead">Current about Information</label>
                    <div class="card mt-2">
                        <div class="card-body">
                            <p class="card-text">
                                {% if not about_detail is None  %}
                                {{ about_detail }}
                                {% else %}
                                There is no about information yet!
                                {% endif %}
                            </p>
                        </div>
                    </div>
    
                </div>
    
                
            </div>
        </div>

    </section>

</div>

samples/mariadmin/templates/mariadmin/sections/image-viewer.html
<div class="offcanvas offcanvas-end" id="view-image-data" role="dialog">
    <div class="offcanvas-header border-bottom">

        <h5 class="offcanvas-title">
            <i class='bx bxs-file-image'></i>
            Image Details
        </h5>

        <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"></button>
    </div>

    <div class="offcanvas-body flex-grow-1">
        <img src="" alt="" id="image-to-display-holder" class="img-fluid">

    </div>
</div>

samples/mariadmin/templates/mariadmin/sections/page-service.html
<div class="row w-100">
    <section id="page-services">
        <div class="card mb-4 mx-2">
            <h5 class="card-header">
                <i class='bx bxs-user-detail bx-flashing-hover me-2'></i>
                Page Services
            </h5>
            
            <div class="card-body">
                <form action="{% url 'messenger:save-page-services' %}" method="post" id="service-register-form" class="pt-0 row g-2">
                    {% csrf_token %}
        
                    <input type="hidden" name="page-id" value="{{ page_id }}">

                    <div id="assets-area">
                        
                    </div>
                    
                    <div class="col-sm-12">
                        <div class="mb-2">
                            <label class="form-label" for="service-name">Service Name</label>
        
                            <div class="input-group input-group-merge">
                                <span class="input-group-text">
                                    <i class='bx bxs-popsicle bx-burst-hover'></i>
                                </span>
                
                                <input type="text" id="service-name" name="service-name" maxlength="50"  class="form-control" placeholder=".i.e Wedding Suits" required>
                            </div>
                
                            <div class="form-text">
                                Provide a simple name for the service, <strong>it cant be recorded more than once</strong>
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="mb-2">
                            <label class="form-label" for="brief-description">Brief Description</label>
        
                            <div class="input-group input-group-merge">
                                <span class="input-group-text">
                                    <i class='bx bxs-quote-alt-left bx-burst-hover'></i>
                                </span>
                
                                <textarea type="text" id="brief-description" name="brief-description" maxlength="180"  class="form-control" placeholder=".i.e We have Perfect Suits for your gentlemen and ladies, we dress you for your days" required></textarea>
                            </div>
                
                            <div class="form-text">
                                Provide a simple description of the service
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="mb-2">
                            <label class="form-label" for="detailed-description">Detailed Description</label>
        
                            <div class="input-group input-group-merge">
                                <span class="input-group-text">
                                    <i class='bx bxs-quote-left bx-burst-hover'></i>
                                </span>
                
                                <textarea type="text" id="detailed-description" name="detailed-description" class="form-control" placeholder=".i.e We have Perfect Suits for your gentlemen and ladies, we dress you for your days, the suits are affordable and come in all color flavours" required></textarea>
                            </div>
                
                            <div class="form-text">
                                Provide a detailed description of the service
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="mb-2">
                            <label class="form-label" for="service-image">Service/Product Image</label>
        
                            <div class="input-group input-group-merge">
                                <span class="input-group-text">
                                    <i class='bx bx-image-alt bx-burst-hover'></i>
                                </span>
                
                                <input type="text" id="service-image" name="service-image" class="form-control" placeholder=".i.e assets/images/Black-suit.jpeg" required>

                                <button type="button" class="btn btn-primary image-selectors" data-output-receiver="service-image">
                                    <i class="bx bxs-image-add bx-burst me-2"></i> Select Image
                                </button>
                            </div>
                
                            <div class="form-text">
                                Select an image for the product or service
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="mb-3">
                            <div class="row">
                                <div class="col-12" id="save-button-holder">
                                    <button type="submit" class="btn btn-primary mb-2 w-100">
                                        <i class="bx bxs-check-circle bx-burst-hover me-2"></i> Save Service
        
                                    </button>
                                </div>

                                <div class="col-6 d-none" id="cancel-button-holder">
                                    <button type="button" class="btn btn-outline-secondary mb-2 w-100" id="cancel-edit-button">
                                        <i class="bx bxs-x-circle bx-burst-hover me-2"></i> Cancel Edit
                                    </button>
                                </div>

                            </div>
                        </div>
                    </div>


                </form>

                <hr>

                <div class="mt-5">
                    <table class="table" id="services-table">
                        <thead>
                            <tr>
                                <th>No.</th>
                                <th>Service Name</th>
                                <th>Controls</th>
                            </tr>
                        </thead>

                        <tbody class="table-border-bottom-0">
                            {% for eachService in present_services %}
                            <tr>
                                <td>
                                    <strong>{{ forloop.counter  }}</strong>
                                </td>
    
                                <td>{{ eachService.name }}</td>
    
                                <td>
                                <div class="dropdown">
                                    <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown"><i class="bx bx-dots-vertical-rounded"></i></button>
                                    
                                    <div class="dropdown-menu">

                                        <form action="#" id="fetch-{{ eachService.id }}">
                                            {% csrf_token %}
                                        </form>

                                        <a class="dropdown-item service-viewer-trigger" href="#" data-service-id="{{ eachService.id }}"><i class="fa fa-eye bx-burst me-1"></i> Edit / View</a>
                                    
                                        <hr class="dropdown-divider">

                                        <a class="dropdown-item" href="{% url 'messenger:wipe-page-service' eachService.id %}"><i class="bx bx-trash bx-burst me-1"></i> Delete Service</a>

                                    </div>
                                </div>
                                </td>
                            </tr>
    
                            {% empty %}
    
                            <p class="lead">No Services recorded yet</p>
    
                            {% endfor %}
                        </tbody>
                    </table>

                    <div class="form-text">
                        The above services appear on the vendors page
                    </div>
                </div>

            </div>

        </div>

    </section>
</div>

samples/mariadmin/templates/mariadmin/sections/services-section.html
<div class="row w-100">
    <section id="services-section">
        <div class="card mb-4 mx-2">
            <h5 class="card-header"><i class="fa-brands fa-servicestack me-2"></i> Available Services</h5>
            <div class="card-body demo-vertical-spacing demo-only-element">
                <div class="mb-4">
                    <form action="{% url 'messenger:edit-website' 7 %}" method="post">
                        {% csrf_token %}
                        <label for="service-name" class="form-label">add new service</label>
                        <div class="input-group">
                            <span class="input-group-text">Service Name & Details</span>
                            <input type="text" id="service-name" name="service-name" placeholder="i.e. Restaurant" class="form-control" required>
                            <textarea class="form-control" name="service-details" placeholder="i.e. We have a perfect spot for your dinners" required></textarea>
                            <button class="btn btn-outline-primary" type="submit">
                                <i class="fa-solid fa-circle-plus me-2"></i></i> Save
                            </button>
                        </div>
                        
                        <div class="form-text">
                            Note: A service can not be added more than once
                        </div>
                    </form>
                </div>
    
                <div class="mb-4">
                    <label for="defaultFormControlInput" class="form-label">REGISTERED SERVICES</label>
    
                    <table class="table">
                        <thead>
                          <tr>
                            <th>Service Name</th>
                            <th>Service Details</th>
                            <th>Preview</th>
                          </tr>
                        </thead>
                        <tbody class="table-border-bottom-0">
                            {% if services %}
                                {% for eachService in services %}
                                    <tr>
                                        <td>{{ eachService.name }}</td>
                                        <td>{{ eachService.details }}</td>
                                        <td>
                                            <button class="btn bg-transparent text-dark">
                                                <i class="fa-solid fa-expand service-view-button" data-service-name="{{ eachService.name }}" data-service-details="{{ eachService.details }}"></i>
                                            </button>
                                        </td>
                
                                        <td>
                                            <div class="dropdown">
                                                <button type="button" class="btn p-0 dropdown-toggle hide-arrow" data-bs-toggle="dropdown"><i class="bx bx-dots-vertical-rounded"></i></button>
                                                <div class="dropdown-menu">
                                                    <a class="dropdown-item" href="{% url 'messenger:wipe-service' eachService.id %}"><i class="bx bx-trash me-1"></i> Delete</a>
                                                </div>
                                            </div>
                                        </td>
                                    </tr>

                                {% endfor %}
                            {% else %}
                                <p class="lead">No Services Yet</p>
                            {% endif %}
                        </tbody>
                    </table>
                </div>
    
                
            </div>
        </div>
    </section>
</div>