samples/messenger/urls.py
from django.urls import path

from django.views.generic import RedirectView

from . import views

app_name = 'messenger'

urlpatterns = [
    path('', views.websiteHomePage, name='welcome'),

    path('login/', views.homePage, name='home'),

    path('update-avatar/', views.updateUserAvatar, name='update-avatar'),
    
    path('deactivate-account/', views.deactivateUserAccount, name='deactivate-account'),

    path('save-venue-image/', views.saveVenueImage, name='write-venue-image'),

    path('delete-venue-image/', views.deleteVenueImage, name='delete-venue-image'),

    path('fetch-venue-images/', views.findVenueImages, name='get-venue-images'),

    path('reset/', views.getResetCodeViaEmail, name='start-reset'),

    path('submit-reset-code/', views.displayResetPage, name='collect-reset-code'),

    path('reset-password/', views.resetUserPassword, name='password-reset'),

    path('search-by-district/', views.viewServicesByDistrict, name='search-by-district'),

    path('signup/', views.registerPage, name='register'),

    path('about-us/', views.aboutPage, name='about'),

    path('venues/', views.venuePage, name='venue'),

    path('venue-detail/<str:venueName>/', views.viewVenueDetails, name='venue-details'),
    
    path('fetch-venue-edit-details/', views.extractVenueEditDetails, name='venue-edit-details'),

    path('chat/', views.chatPage, name='chat-page'),

    path('blog-editor/', views.blogEditorPage, name='blog-editor'),

    path('blog-page/<int:pageId>', views.viewBlogPostDetails, name='blog-post'),

    path('delete-post/<int:postCategoryId>/', views.deleteSpecificPostCategory, name='delete-post'),

    path('delete-post-data/<int:postItemId>/', views.deleteSpecificPostItem, name='delete-post-data'),

    path('email/', views.emailPage, name='email-page'),

    path('submit-message/<int:userGroup>/', views.submitChatMessage, name='chat-upload'),

    path('gallery/', views.galleryPage, name='gallery'),

    path('gallery-manager/', views.galleryControlPanel, name='gallery-control'),

    path('update-image-state/', views.updateGalleryImageState, name='gallery-image-control'),

    path('page-registry/', views.viewPageRegistry, name='page-registry'),

    path('services/', views.servicesPageView, name='restaurant'),

    path('services/<str:serviceCategory>/', views.viewServicesByCategory, name='services-by-category'),

    path('blog/', views.blogPostPage, name='blog'),

    path('submit-comment/', views.submitPostComment, name='submit-comment'),

    path('get-post-data/', views.getPostInformation, name='get-post-data'),

    path('contact/', views.contactPage, name='contact'),

    path('book-mariahill-gardens/', views.bookMariahillGardens, name='book-gardens'),

    path('record-booking/', views.recordBookingInformation, name='record-booking'),

    path('logout/', views.logoutUser, name='logout-user'),

    path('uploads/', views.fileManagerPage, name='file-manager'),

    path('alter-primary-credentials/', views.managePrimaryCredentials, name='primary-credentials'),

    path('user-access/', views.manageNextOfKins, name='next-of-kins'),
    
    # bookings
    path('booking-requests/', views.manageBookingRequests, name='booking-requests'),

    path('register-admin/', views.registerNewAdmin, name='register-admin'),

    path('wipe-admin-user/<int:adminId>', views.ripOffAdmin, name='wipe-administrator'),

    path('get-admin-profile/', views.fetchAdminDetail, name='get-admin-data'),

    path('alter-admin-profile/', views.changeAdminPermissions, name='alter-admin-profile'),

    path('alter-local-user-credentials/', views.updateUserCredentials, name='update-local-user-credentials'),

    path('grant-admin-access/<int:idOfAdmin>/', views.giveSecondaryAdminAccess, name='grant-admin-access'),

    path('delete-upload/<int:imageId>/', views.deleteSpecificUpload, name='wipe-upload'),

    path('delete-thread/', views.wipeMessagesThread, name='wipe-thread'),

    path('delete-service/<int:serviceId>/', views.deleteSpecificService, name='wipe-service'),

    path('delete-page-category/<int:categoryId>/', views.deletePageCategory, name='wipe-page-category'),

    path('delete-venue/<int:venueId>/', views.deleteSpecificVenue, name='wipe-venue'),

    path('delete-contact/<int:contactId>/<int:whoseContact>/', views.deleteSpecificContact, name='wipe-contact'),

    path('delete-comments/<int:postId>/', views.deletePostComments, name='delete-comments'),

    path('delete-reply/<int:replyId>/', views.deleteSpecificReply, name='wipe-reply'),

    path('delete-vendor-page/<int:pageId>/', views.deleteVendorPage, name='wipe-vendor-page'),

    path('delete-all-chats/<str:userName>/', views.deleteChatsForGivenUser, name='wipe-all-chats'),

    path('delete-testimonial/<int:testimonialId>/', views.deleteSpecificTestimonial, name='wipe-testimonial'),

    path('editor/<int:sectionId>/', views.makeWebsiteEdit, name='edit-website'),

    path('update-venue/', views.updateVenueFeaturedStatus, name='update-venue'),

    path('update-post-state/', views.updatePostFeaturedState, name='update-post'),

    path('get-user-chats/', views.getNewUserChats, name='get-chats'),

    path('submit-message/', views.submitSimpleMessage, name='submit-message'),

    path('submit-page-category/', views.registerPageCategory, name='submit-page-category'),

    path('get-thread/', views.getMessageThreadData, name='get-thread'),

    path('submit-reply/', views.submitAdminReply, name='send-reply'),

    path('save-page/', views.recordNewVendorPage, name='save-page'),

    path('save-form-detail/', views.recordBookingFormDetail, name='booking-form-detail'),

    path('get-page-data/', views.fetchPageMeta, name='get-page-meta'),

    path('page-manager/<int:pageId>', views.manageThirdPartyPage, name='manage-vendor-page'),

    path('save-page-details/', views.savePageDetails, name='save-page-details'),

    path('save-page-handles/', views.savePageHandles, name='save-page-handles'),

    path('save-page-services/', views.savePageServices, name='save-page-services'),

    path('delete-page-service/<int:serviceId>', views.wipePageService, name='wipe-page-service'),

    path('get-service-meta/', views.fetchServiceInformation, name='get-service-info'),

    path("service-providers/<str:vendorPageName>/", views.viewVendorPage, name='vendor-page'),

]

samples/samples/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("messenger.urls")),
    path("accounts/", include("userenv.urls")),
    path("control/", include("mariadmin.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

samples/mariasite/models.py
from django.db import models

# Create your models here.

samples/mariasite/views.py
from django.shortcuts import render

# Create your views here.

samples/mariasite/templates/mariasite/core/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />

    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />

    <title>Maria Hill Gardens | Make Memories With Us</title>

    <meta name="description" content="Create unforgettable memories with us" />
    <meta
      name="keywords"
      content="unforgettable, memories, maria hill, maria hill gardens, maria hill events, maria hill entebbe"
    />

    <!-- online -->
    <link rel="preconnect" href="https://fonts.gstatic.com" />

    <link
      href="https://fonts.googleapis.com/css2?family=Nunito:wght@300;400;600;700&amp;family=Old+Standard+TT:ital,wght@0,400;0,700;1,400&amp;display=swap"
      rel="stylesheet"
    />

    <link
      rel="icon"
      type="image/x-icon"
      href="{% static 'mariadmin/local-update/frest/admin/assets/img/favicon/mariahill.png' %}"
    />

    <!-- fonts -->
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Imperial+Script&family=Playfair:wght@300&display=swap"
      rel="stylesheet"
    />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Pinyon+Script&display=swap"
      rel="stylesheet"
    />

    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=IM+Fell+French+Canon:ital@0;1&display=swap"
      rel="stylesheet"
    />

    <link
      rel="stylesheet"
      href="{% static 'mariadmin/local-update/frest/admin/assets/vendor/fonts/boxicons.css' %}"
    />

    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
    />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/4.5.6/css/ionicons.min.css"
    />

    {% block own_css %} {% endblock %}

    <link
      rel="stylesheet"
      href="{% static 'mariasite/color/site-core/theme/unwind/css/animate.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'mariasite/color/site-core/theme/unwind/css/flaticon.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'mariasite/color/site-core/theme/unwind/css/tiny-slider.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'mariasite/color/site-core/theme/unwind/css/glightbox.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'mariasite/color/site-core/theme/unwind/css/aos.css' %}"
    />

    <link
      rel="stylesheet"
      href="{% static 'mariasite/color/site-core/theme/unwind/css/ancient/ny-fonts.css' %}"
    />

    <link
      rel="stylesheet"
      href="{% static 'mariasite/color/banner/fonts/benedict.css' %}"
    />

    <link
      rel="stylesheet"
      href="{% static 'mariasite/color/site-core/theme/unwind/css/tangerine/tangerine.css' %}"
    />

    <link
      rel="stylesheet"
      href="{% static 'mariasite/color/site-core/theme/unwind/css/lovers-quarrel/lovers-quarrel.css' %}"
    />

    <link
      rel="stylesheet"
      href="{% static 'mariasite/color/site-core/theme/unwind/css/style.css' %}"
    />

    <style>
      @import url(http://fonts.googleapis.com/css?family=Gentium+Book+Basic:400,700,700italic,400italic);

      q,
      blockquote {
        quotes: "“" "”" "‘" "’";
        font-style: italic;
      }

      .french {
        quotes: "«" "»" "‹" "›";
      }

      q:before,
      blockquote:before {
        content: open-quote;
      }

      q:after,
      blockquote:after {
        content: close-quote;
      }

      q:before,
      q:after,
      blockquote:before,
      blockquote:after {
        color: #CAA87B;
        font-size: 1.2em;
      }

      blockquote {
        margin-left: 0;
        padding-left: 1em;
        border-left: 5px solid deepPink;
      }
      .maria-header {
        font-family: "IM Fell French Canon", serif;
        font-size: 1em;
        font-weight: 10 !important;
        line-height: 1.2em;
        display: block;
        color: white;
        margin-bottom: 0 !important;
      }

      .d-none {
        display: none;
      }

      .navbar-logo {
        display: none;
      }

      @media (max-width: 767px) {
        .maria-header {
          font-size: 3em;
          white-space: wrap !important;
        }

        .book-mariahill{
          width: 140px !important;
        }

        #tabs-holder{
          display: none;
        }
      }

      @media (min-width: 768px) {
        .maria-header {
          font-size: 4em;
          white-space: wrap;
        }
      }

      @media screen and (min-width: 768px) and (max-width: 792px) {
        .maria-header {
          font-size: 4em;
          white-space: wrap;
        }
      }

      @media (min-width: 1001px) {
        .navbar-logo {
          display: block;
        }
      }

      .template-customizer-open-btn-services {
        position: fixed;
        top: 250px;
        left: 0;
        z-index: 99999999px;
        display: block;
        width: 47px;
        height: 42px;
        border: none;
        border-top-right-radius: 45%;
        border-bottom-right-radius: 45%;
        background: #c5a880;
        color: #fff !important;
        text-align: center;
        font-size: 27px !important;
        line-height: 42px;
        opacity: 1;
      }

      @media (max-width: 991.98px) {
        .template-customizer-open-btn-services {
          top: 120px;
        }
      }

      @media (min-width: 991.98px) {
        .maria-header {
          font-size: 4em;
          white-space: nowrap;
        }
      }

      .template-customizer-open-btn {
        position: fixed;
        top: 180px;
        right: 0;
        z-index: 99999999px;
        display: block;
        width: 47px;
        height: 42px;
        border-top-left-radius: 45%;
        border-bottom-left-radius: 45%;
        background: #333;
        color: #fff !important;
        text-align: center;
        font-size: 27px !important;
        line-height: 42px;
        opacity: 1;
      }

      .book-now-btn {
        position: fixed;
        top: 280px;
        left: -30px;
        z-index: 99999999px;
        display: block;

        text-align: center;
        font-size: 27px !important;
        line-height: 42px;
        opacity: 1;
      }

      @media (max-width: 991.98px) {
        .template-customizer-open-btn {
          top: 145px;
        }

        .book-now-btn {
          top: 150px;
        }

      }

      .banner-sub-title {
        font-family: "Benedict";
        font-size: 30px;
      }

      .venue-description{
        margin-top: 1rem !important;
        font-family: "Benedict";
        font-size: 20px;
        background: rgba(34, 34, 34, 0.5);
        border-radius: 7px;
        padding-left: 1rem;
        padding-right: 1rem;


      }

      .venue-name-featured{
        margin-bottom: 1.2rem !important;
        padding-top: 0.7rem;
        padding-bottom: 0.7rem;
        padding-left: 1rem;
        padding-right: 1rem;
        border-radius: 50px;
        background: rgba(34, 34, 34, 0.5);
      }
    </style>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg ftco-navbar-light">
      <div class="container-xl">
        <!--  -->
        <a
          class="navbar-brand navbar-logo"
          href="{% url 'messenger:welcome' %}"
        >
          <img
            src="{% static 'mariasite/color/site-core/theme/unwind/images/white-maria.png' %}"
            style="width: 150px; height: auto"
            alt="Logo"
          />
        </a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="fa fa-bars"></span> Menu
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link active"
                data-id="1"
                href="{% url 'messenger:welcome' %}"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" data-id="2" href="{% url 'messenger:about' %}"
                >About</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" data-id="3" href="{% url 'messenger:venue' %}"
                >Venues</a
              >
            </li>

            <li class="nav-item">
              <a
                class="nav-link"
                data-id="4"
                href="{% url 'messenger:restaurant' %}"
                >Services</a
              >
            </li>

            <li class="nav-item">
              <a class="nav-link" data-id="5" href="{% url 'messenger:blog' %}"
                >Blog</a
              >
            </li>
            <li class="nav-item">
              <a
                class="nav-link"
                data-id="5"
                href="{% url 'messenger:contact' %}"
                >Contact</a
              >
            </li>

            {% if request.user.is_authenticated %}

            <li class="nav-item bg-sm-transparent bg-secondary">
              <a class="nav-link" data-id="6" href="{% url 'messenger:home' %}">
                Account
              </a>
            </li>
            {% else %}

            <li class="nav-item bg-sm-transparent bg-secondary">
              <a class="nav-link" data-id="6" href="{% url 'messenger:home' %}">
                Login
              </a>
            </li>

            {% endif %}
          </ul>
        </div>
      </div>
    </nav>

    {% block page_main %} {% endblock %}
    {% include 'mariasite/sections/footer-section.html' %}
    {% if hide_gallery %}
    {% else %}
    {% include 'mariasite/core/side-button.html' %} {% endif %}
    {% include 'mariasite/core/services-side-button.html' %}

    <script src="{% static 'mariasite/color/site-core/theme/unwind/js/new/bootstrap.min.js' %}"></script>

    <script src="{% static 'mariasite/color/site-core/theme/unwind/js/tiny-slider.js' %}"></script>
    <script src="{% static 'mariasite/color/site-core/theme/unwind/js/glightbox.min.js' %}"></script>
    <script src="{% static 'mariasite/color/site-core/theme/unwind/js/aos.js' %}"></script>
    <script src="{% static 'mariasite/color/site-core/theme/unwind/js/main.js' %}"></script>
    <script src="{% static 'mariasite/color/site-core/theme/unwind/js/custom-script.js' %}"></script>
    <script src="{% static 'mariasite/color/site-core/theme/unwind/js/service-home.js' %}"></script>

    {% block own_js %} {% endblock %}
  </body>
</html>

samples/mariasite/templates/mariasite/core/services-side-button.html
<button class="template-customizer-open-btn-services text-white" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasWithBackdrop" aria-controls="offcanvasWithBackdrop" tabindex="-1">
    <i class="bx bxs-paper-plane bx-burst-hover" style="font-size: 20px;"></i>
</button>


<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasWithBackdrop" aria-labelledby="offcanvasWithBackdrop" aria-modal="true" role="dialog">
    <div class="offcanvas-header border-bottom bg-primary">
        <h5 id="offcanvasStartLabel" class="offcanvas-title text-white">Other Service Providers</h5>
        <button type="button" class="btn-close text-reset text-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>

    <div class="offcanvas-body my-auto mx-0 flex-grow-0">
        <a role="button" href="{% url 'messenger:restaurant' %}" class="btn btn-primary mt-5 mb-2 d-grid w-100">
            <i class="fa fa-paper-plane"></i>
            View All
        </a>
        
        <div class="mb-3">
            <ol class="list-group list-group-numbered">
                {% for eachCategoryObject in page_category_meta %}
                    <li class="list-group-item d-flex justify-content-between align-items-start">
                        
                        <div class="ms-2 me-auto">
                            <div class="fw-bold">
                                <a href="{% url 'messenger:services-by-category' eachCategoryObject.name %}">{{ eachCategoryObject.name }}</a>
                            </div>
                        </div>

                        <span class="badge bg-primary rounded-pill">
                            <a href="{% url 'messenger:services-by-category' eachCategoryObject.name %}" style="color: white;">{{ eachCategoryObject.count }}</a>
                        </span>
                    </li>

                {% empty %}
                    <p class="lead">No Services Yet</p>

                {% endfor %}

            </ol>
        </div>

        <!-- create  -->
        <!-- <p class="text-center">
            Services displayed above can be handy on your event, 
        </p> -->
    

        <!-- <button type="button" class="btn btn-label-secondary d-grid w-100" data-bs-dismiss="offcanvas">CLOSE</button> -->
    </div>
</div>

samples/mariasite/templates/mariasite/core/side-button.html
{% load static  %}

{% if booking_section %}
<a href="{% url 'messenger:gallery' %}" class="template-customizer-open-btn text-white" data-bs-toggle="tooltip" data-bs-placement="top" title="View Our Gallery" tabindex="-1">
  <i class="fa fa-camera-retro" style="font-size: 20px;"></i>
</a>
{% endif %}


<a href="{% url 'messenger:book-gardens' %}#booking-form" class="book-now-btn text-white" data-bs-toggle="tooltip" data-bs-placement="top" title="View Our Gallery" tabindex="-1">
  <img
  src="{% static 'mariasite/color/site-core/theme/unwind/images/logos/logo_svg.svg' %}"
  style="width: 200px; height: auto"
  class="book-mariahill"
  alt="Logo"
/>
</a>