samples/mariadmin/urls.py
from django.urls import path

from . import views

app_name = 'admin_panel'


urlpatterns = [
    path("", view=views.adminHomePage, name='admin-home'),
    path('addcategory/', views.registerCategory, name='insert-category'),
    path('deletecategory/<int:categoryId>', views.deleteCategory, name='delete-category'),
]

samples/messenger/urls.py
from django.urls import path

from django.views.generic import RedirectView

from . import views

app_name = 'messenger'

urlpatterns = [
    path('', views.websiteHomePage, name='welcome'),

    path('login/', views.homePage, name='home'),

    path('update-avatar/', views.updateUserAvatar, name='update-avatar'),
    
    path('deactivate-account/', views.deactivateUserAccount, name='deactivate-account'),

    path('save-venue-image/', views.saveVenueImage, name='write-venue-image'),

    path('delete-venue-image/', views.deleteVenueImage, name='delete-venue-image'),

    path('fetch-venue-images/', views.findVenueImages, name='get-venue-images'),

    path('reset/', views.getResetCodeViaEmail, name='start-reset'),

    path('submit-reset-code/', views.displayResetPage, name='collect-reset-code'),

    path('reset-password/', views.resetUserPassword, name='password-reset'),

    path('search-by-district/', views.viewServicesByDistrict, name='search-by-district'),

    path('signup/', views.registerPage, name='register'),

    path('about-us/', views.aboutPage, name='about'),

    path('venues/', views.venuePage, name='venue'),

    path('venue-detail/<str:venueName>/', views.viewVenueDetails, name='venue-details'),
    
    path('fetch-venue-edit-details/', views.extractVenueEditDetails, name='venue-edit-details'),

    path('chat/', views.chatPage, name='chat-page'),

    path('blog-editor/', views.blogEditorPage, name='blog-editor'),

    path('blog-page/<int:pageId>', views.viewBlogPostDetails, name='blog-post'),

    path('delete-post/<int:postCategoryId>/', views.deleteSpecificPostCategory, name='delete-post'),

    path('delete-post-data/<int:postItemId>/', views.deleteSpecificPostItem, name='delete-post-data'),

    path('email/', views.emailPage, name='email-page'),

    path('submit-message/<int:userGroup>/', views.submitChatMessage, name='chat-upload'),

    path('gallery/', views.galleryPage, name='gallery'),

    path('gallery-manager/', views.galleryControlPanel, name='gallery-control'),

    path('update-image-state/', views.updateGalleryImageState, name='gallery-image-control'),

    path('page-registry/', views.viewPageRegistry, name='page-registry'),

    path('services/', views.servicesPageView, name='restaurant'),

    path('services/<str:serviceCategory>/', views.viewServicesByCategory, name='services-by-category'),

    path('blog/', views.blogPostPage, name='blog'),

    path('submit-comment/', views.submitPostComment, name='submit-comment'),

    path('get-post-data/', views.getPostInformation, name='get-post-data'),

    path('contact/', views.contactPage, name='contact'),

    path('book-mariahill-gardens/', views.bookMariahillGardens, name='book-gardens'),

    path('record-booking/', views.recordBookingInformation, name='record-booking'),

    path('logout/', views.logoutUser, name='logout-user'),

    path('uploads/', views.fileManagerPage, name='file-manager'),

    path('alter-primary-credentials/', views.managePrimaryCredentials, name='primary-credentials'),

    path('user-access/', views.manageNextOfKins, name='next-of-kins'),
    
    # bookings
    path('booking-requests/', views.manageBookingRequests, name='booking-requests'),

    path('register-admin/', views.registerNewAdmin, name='register-admin'),

    path('wipe-admin-user/<int:adminId>', views.ripOffAdmin, name='wipe-administrator'),

    path('get-admin-profile/', views.fetchAdminDetail, name='get-admin-data'),

    path('alter-admin-profile/', views.changeAdminPermissions, name='alter-admin-profile'),

    path('alter-local-user-credentials/', views.updateUserCredentials, name='update-local-user-credentials'),

    path('grant-admin-access/<int:idOfAdmin>/', views.giveSecondaryAdminAccess, name='grant-admin-access'),

    path('delete-upload/<int:imageId>/', views.deleteSpecificUpload, name='wipe-upload'),

    path('delete-thread/', views.wipeMessagesThread, name='wipe-thread'),

    path('delete-service/<int:serviceId>/', views.deleteSpecificService, name='wipe-service'),

    path('delete-page-category/<int:categoryId>/', views.deletePageCategory, name='wipe-page-category'),

    path('delete-venue/<int:venueId>/', views.deleteSpecificVenue, name='wipe-venue'),

    path('delete-contact/<int:contactId>/<int:whoseContact>/', views.deleteSpecificContact, name='wipe-contact'),

    path('delete-comments/<int:postId>/', views.deletePostComments, name='delete-comments'),

    path('delete-reply/<int:replyId>/', views.deleteSpecificReply, name='wipe-reply'),

    path('delete-vendor-page/<int:pageId>/', views.deleteVendorPage, name='wipe-vendor-page'),

    path('delete-all-chats/<str:userName>/', views.deleteChatsForGivenUser, name='wipe-all-chats'),

    path('delete-testimonial/<int:testimonialId>/', views.deleteSpecificTestimonial, name='wipe-testimonial'),

    path('editor/<int:sectionId>/', views.makeWebsiteEdit, name='edit-website'),

    path('update-venue/', views.updateVenueFeaturedStatus, name='update-venue'),

    path('update-post-state/', views.updatePostFeaturedState, name='update-post'),

    path('get-user-chats/', views.getNewUserChats, name='get-chats'),

    path('submit-message/', views.submitSimpleMessage, name='submit-message'),

    path('submit-page-category/', views.registerPageCategory, name='submit-page-category'),

    path('get-thread/', views.getMessageThreadData, name='get-thread'),

    path('submit-reply/', views.submitAdminReply, name='send-reply'),

    path('save-page/', views.recordNewVendorPage, name='save-page'),

    path('save-form-detail/', views.recordBookingFormDetail, name='booking-form-detail'),

    path('get-page-data/', views.fetchPageMeta, name='get-page-meta'),

    path('page-manager/<int:pageId>', views.manageThirdPartyPage, name='manage-vendor-page'),

    path('save-page-details/', views.savePageDetails, name='save-page-details'),

    path('save-page-handles/', views.savePageHandles, name='save-page-handles'),

    path('save-page-services/', views.savePageServices, name='save-page-services'),

    path('delete-page-service/<int:serviceId>', views.wipePageService, name='wipe-page-service'),

    path('get-service-meta/', views.fetchServiceInformation, name='get-service-info'),

    path("service-providers/<str:vendorPageName>/", views.viewVendorPage, name='vendor-page'),

]

samples/samples/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static

from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("messenger.urls")),
    path("accounts/", include("userenv.urls")),
    path("control/", include("mariadmin.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

samples/mariadmin/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth.decorators import login_required

from django.views.decorators.cache import cache_control

from django.http import JsonResponse

from django.contrib import messages

from django.http import HttpRequest

from .models import (Category, 
                    AboutHeading, AboutDetails, LeftCard, 
                    RightCard, OfferedService, MiddleGrid, 
                    VenueItem, Testimonial, StatisticsMeta, 
                    Contacts, WebsiteHeadingImage, EventsServicesContacts, 
                    gardensTourVideoLink, BookingFormDetail
                    )

from messenger.views import ControlUtils



def getAdminHomeContext():
    # get available categories
    availableCategories = [
            {
                'category': str(eachCategory),
                'tag': eachCategory.pk
            } for eachCategory in Category.objects.all()
        ]
    
    # get the banner image
    bannerImage = WebsiteHeadingImage.objects.all().first()
    
    videoLinkUrl = gardensTourVideoLink.objects.all().first()
    
    # get the booking form object
    bookingFormObject = BookingFormDetail.objects.all().first()
    
    bookingFormText, bookingFormImage = bookingFormObject.formText, bookingFormObject.imageUrl
    
    adminContext = {
        "contact_form_text": bookingFormText,
        "form_side_image":  bookingFormImage,
        'tour_video_link': videoLinkUrl.videoUrl if videoLinkUrl else None,
        'categories': availableCategories,
        'banner_image': bannerImage.imageUrl if bannerImage else None,
        'heading': str(AboutHeading.objects.all().first()) if AboutHeading.objects.all().first() else None,
        'about_detail': str(AboutDetails.objects.all().first()) if AboutDetails.objects.all().first() else None,
        'left_card_data': {'heading': LeftCard.objects.all().first().leftCardHeading, 'text': LeftCard.objects.all().first().leftCardText, 'image': LeftCard.objects.all().first().leftCardImageUrl} if LeftCard.objects.all().first() else None,
        'right_card_data': {'heading': RightCard.objects.all().first().rightCardHeading, 'text': RightCard.objects.all().first().rightCardText, 'image': RightCard.objects.all().first().rightCardImageUrl} if RightCard.objects.all().first() else None,
        'uploads': ControlUtils().getUploadsData(),
        # 
        'services': [
            {'name': eachService.serviceName, 'details': eachService.serviceDetails, 'id':eachService.pk} for eachService in OfferedService.objects.all()],
        'ribbon': {
            'heading': MiddleGrid.objects.all().first().gridTitle,
            'message': MiddleGrid.objects.all().first().gridMessage,
            'text': MiddleGrid.objects.all().first().gridButtonText,
            'url': MiddleGrid.objects.all().first().gridRedirectionUrl
            },
        'venues': [
                {
                    'name': eachVenue.venueName,
                    'capacity': eachVenue.venueCapacity,
                    'description': eachVenue.venueDescription.capitalize(),
                    'featured': eachVenue.isFeatured,
                    'id': eachVenue.pk
                } for eachVenue in VenueItem.objects.all()
            ],
        'testimonials': [
                {
                    'name': eachTestimonial.guestName,
                    'comment': eachTestimonial.guestComment,
                    'position': eachTestimonial.guestPosition,
                    'image': eachTestimonial.guestImageUrl,
                    'id': eachTestimonial.pk
                } for eachTestimonial in Testimonial.objects.all()
            ],
        'statistics': {
                'guests': StatisticsMeta.objects.all().first().happyGuests,
                'events': StatisticsMeta.objects.all().first().hostedEvents,
                'staff': StatisticsMeta.objects.all().first().staffCount,
                'venues': StatisticsMeta.objects.all().first().venueCount
            
            },
        'contacts': [
                {
                    'type': eachContact.contactType.capitalize(),
                    'value': eachContact.contactValue,
                    'id': eachContact.pk,
                    'kind': 1
                } for eachContact in Contacts.objects.all()
            ],
        'events_contacts': [
                {
                    'type': eachContact.contactType.capitalize(),
                    'value': eachContact.contactValue,
                    'id': eachContact.pk,
                    'kind': 2
                } for eachContact in EventsServicesContacts.objects.all()
            ]
        
        }


    return adminContext

def determinePageRoute(accessTag):
    # 'website': True,
    # 'blog': True,
    # 'pages': True,
    # 'comms': True,
    # 'users': True
    if accessTag == 'blog':
        redirectObject = redirect("messenger:blog-editor")
        
    elif accessTag == 'pages':
        redirectObject = redirect("messenger:page-registry")
        
    elif accessTag == 'comms':
        redirectObject = redirect("messenger:chat-page")
        
    else:
        redirectObject = redirect("messenger:next-of-kins")
        
    return redirectObject

def getFirstPermission(request:HttpRequest):
    # get first permission
    for eachPermission, permissionValue in request.session['allowed_pages'].items():
        if permissionValue is True:
            firstPermission = eachPermission
            break
        

    return firstPermission
    
    
        
    

@login_required(login_url='messenger:home')
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def adminHomePage(request):
    # determine if its the home page to be displayed
    if request.session['allowed_pages']['website'] is True:
        # load
        adminContext = getAdminHomeContext()
        
        return render(request, "mariadmin/index.html", context=adminContext)
    
    else:
        # determine redirection route
        firstPermission = getFirstPermission(request=request)
        
        # get a route
        responseObject = determinePageRoute(accessTag=firstPermission)
        
        return responseObject


    
    
    



@login_required(login_url='messenger:home')
def registerCategory(request):
    if request.method == "POST":
        # get the submitted data
        submittedData = request.POST.dict()
        
        # get the category name
        reportedCategoryName  = submittedData['category-name'].lower().capitalize()
        
        isItDuplicate = Category.objects.filter(modelName=reportedCategoryName).first()
        
        if isItDuplicate:
            # alert error
            messages.warning(request, "Category Name exists already!")
        
        else:
            # create the new category
            newCategory = Category.objects.create(modelName=reportedCategoryName)
            
            # save the new category
            newCategory.save()
            
            # alert success
            messages.success(request, "Category name was registered!")
            
        return redirect("admin_panel:admin-home")
    
    else:
        # print("Here")
        
        return JsonResponse(
            dict(
                message = 'resource not accessible'
            )
        )
        
@login_required(login_url='messenger:home')
def deleteCategory(request, categoryId):
    # get and delete the object
    categoryToDelete = get_object_or_404(Category, pk=categoryId)
    
    # delete the category
    categoryToDelete.delete()
    
    return redirect("admin_panel:admin-home")

samples/mariadmin/templates/mariadmin/alert-toast.html
{% if messages %}
    {% for eachMessage in messages %}
      <div class="bs-toast toast toast-ex animate__animated my-2 fade animate__fadeInUp show" role="alert" aria-live="assertive" aria-atomic="true" data-bs-delay="2000">
          <div class="toast-header bg-warning">
            <div class="me-auto fw-semibold">Alert</div>
            <small><strong>Maria Hill Management</strong></small>
            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
          </div>
          <div class="toast-body" id="toastbody">
            {{ eachMessage.message }}
          </div>
      </div>
    {% endfor %}
  {% endif %}

samples/mariadmin/templates/mariadmin/goto-reset.html
{% extends "mariadmin/reglog-layout.html" %}

{% block content %}

    <div class="authentication-wrapper authentication-basic px-4">
        {% include "mariadmin/alert-toast.html" %}

        <div class="authentication-inner py-4">
            <!-- Get reset via Email -->
            <div class="card">
                <div class="card-body">
                    <div class="app-brand justify-content-center">
                        <a href="#" class="app-brand-link gap-2">
                          <span class="app-brand-logo demo">
                          </span>
                          <span class="app-brand-text demo h3 mb-0 fw-bold">Maria Hill Gardens <i class='bx bxs-check-shield ms-1'></i> </span>
                        </a>
                    </div>

                    <!-- /Logo -->
                    <h4 class="mb-2">Wish to reset your password? 🤔</h4>

                    <p class="text-start">
                        Provide a valid email address that is attached to your account via which you will request a reset code
                    </p>

                    <form action="{% url 'messenger:start-reset' %}" method="post">
                        {% csrf_token %}

                        <div class="mb-3 fv-plugins-icon-container">
                            <label for="reset-email" class="form-label">Enter Account Email</label>
                            
                            <input type="email" class="form-control" id="reset-email" name="reset-email" placeholder="Enter your account email address" autofocus="" required
                            {% if reset_email %}
                                value="{{ reset_email }}"
                            {% endif %}
                            >
                            
                            <div class="fv-plugins-message-container invalid-feedback"></div>
                        </div>
    
                        <button class="btn btn-primary w-100 my-3" type="submit">
                            <i class='bx bx-refresh bx-burst-hover me-1'></i> Get Reset Code
                        </button>
                    </form>

                    <p class="text-center">Remembered you password?
                        <a href="{% url 'messenger:home' %}">
                        Login
                        </a>
                    </p>
                    
                </div>
            </div>
            <!-- Get reset via Email -->
        </div>
        
    </div>

{% endblock %}

samples/mariadmin/templates/mariadmin/index.html
{% extends "mariadmin/home-layout.html" %}

{% load static %}

{% block page_css %}
    <link
    rel="stylesheet"
    href="{% static 'mariadmin/local-update/frest/admin/assets/vendor/libs/swiper/swiper.css' %}"
    />

    <link
    rel="stylesheet"
    href="{% static 'mariadmin/local-update/frest/admin/assets/vendor/css/pages/ui-carousel.css' %}"
    />

{% endblock %}



{% block page_content %}

    {% include "mariadmin/sections/banner-image-editor.html" %}

    {% include "mariadmin/sections/gardens-tour-editor.html" %}

    {% include "mariadmin/sections/booking-form.html" %}

    {% include "mariadmin/sections/event-categories.html" %}

    {% include "mariadmin/sections/about-meta.html" %}

    {% include "mariadmin/sections/about-left-meta.html" %}

    <!-- {% include "mariadmin/sections/services-section.html" %} -->

    {% include "mariadmin/sections/ribbon-section.html" %}

    {% include "mariadmin/sections/venues-section.html" %}

    {% include "mariadmin/sections/testimonial-section.html" %}

    {% include "mariadmin/sections/stat-section.html" %}

    {% include "mariadmin/sections/contact-section.html" %}

    {% include "mariadmin/sections/image-section.html" %}

    {% include "mariadmin/sections/service-viewer.html" %}

    {% include "mariadmin/sections/venue-viewer.html" %}


{% endblock %}

{% block vendor_js %} 
    <script src="{% static 'mariadmin/local-update/frest/admin/assets/vendor/libs/swiper/swiper.js' %}"></script>

{% endblock %}


{% block page_js %}
    <script src="{% static 'mariadmin/local-update/frest/admin/assets/js/image-control.js' %}"></script>

    <script src="{% static 'mariadmin/local-update/frest/admin/assets/js/ui-carousel.js' %}"></script>

    <script src="{% static 'mariadmin/local-update/frest/admin/assets/js/service-viewer.js' %}"></script>

    <!-- <script src="{% static 'mariadmin/local-update/frest/admin/assets/js/image-display.js' %}"></script> -->

    <script src="{% static 'mariadmin/local-update/frest/admin/assets/js/featured-control.js' %}"></script>

    <script src="{% static 'mariadmin/local-update/frest/admin/assets/js/venue-viewer.js' %}"></script>


{% endblock %}

samples/mariadmin/templates/mariadmin/login.html
{% extends "mariadmin/reglog-layout.html" %}

{% block content %}
  <div class="container-xxl">

    {% include "mariadmin/alert-toast.html" %}


    <div class="authentication-wrapper authentication-basic container-p-y">
      <div class="authentication-inner py-4">
        <!-- Register -->
        <div class="card">
          <div class="card-body">
            <!-- Logo -->
            <div class="app-brand justify-content-center">
              <a href="{% url 'messenger:welcome' %}" class="app-brand-link gap-2">
                <span class="app-brand-logo demo">
                </span>
                <span class="app-brand-text demo h3 mb-0 fw-bold">Mariahill Gardens</span>
              </a>
            </div>
            <!-- /Logo -->
            <h4 class="mb-2">Welcome to Mariahill Gardens 👋</h4>
            <p class="mb-4">
              Please sign-in to your account and start the adventure
            </p>

            <form
              id="formAuthentication"
              class="mb-3"
              action="{% url 'messenger:home' %}"
              method="POST"
            >
              {% csrf_token %}
              <div class="mb-3">
                <label for="email" class="form-label">Email or Username</label>
                <input
                  type="email"
                  class="form-control"
                  id="email"
                  name="email"
                  placeholder="Enter your email or username"
                  autofocus
                />
              </div>
              
              <div class="mb-3 form-password-toggle">
                <div class="d-flex justify-content-between">
                  <label class="form-label" for="password">Password</label>
                  <a href="{% url 'messenger:start-reset' %}">
                    <small>Forgot Password?</small>
                  </a>
                </div>
                <div class="input-group input-group-merge">
                  <input
                    type="password"
                    id="password"
                    class="form-control"
                    name="password"
                    placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
                    aria-describedby="password"
                  />
                  <span class="input-group-text cursor-pointer"
                    ><i class="bx bx-hide"></i
                  ></span>
                </div>
              </div>

              <div class="mb-3 mt-4">
                <button class="btn btn-primary d-grid w-100" type="submit">
                  Sign in
                </button>
              </div>
            </form>

            <p class="text-center">
              <span>New on our platform?</span>
              <a href="{% url 'messenger:register' %}">
                <i class='bx bxs-hand-right bx-burst me-1'></i>
                <span>Create an account</span>
              </a>
            </p>

            <div class="divider my-4">
              <div class="divider-text">+</div>
            </div>

            <div class="d-flex justify-content-center">
              <span>All rights reserved</span>
            </div>
          </div>
        </div>
        <!-- /Register -->
      </div>
    </div>
  </div>
{% endblock %}

samples/mariadmin/templates/mariadmin/password-reset.html
{% extends "mariadmin/reglog-layout.html" %}

{% load static %}

{% block content %}

    <div class="container-xxl">
        <div class="authentication-wrapper authentication-basic container-p-y">
            <div class="authentication-inner py-4">
                <!-- Reset Password -->
                <div class="card">
                    <div class="card-body">

                        
                        <div class="app-brand justify-content-center">
                            <a href="#" class="app-brand-link gap-2">
                            <span class="app-brand-logo demo">
                            </span>
                            <span class="app-brand-text demo h3 mb-0 fw-bold">Maria Hill Gardens <i class='bx bxs-check-shield ms-1'></i> </span>
                            </a>
                        </div>


                        <h4 class="mb-2">Reset Password 🔒</h4>

                        <p class="mb-4">for <span class="fw-bold">{{ reset_email }}</span></p>
                        
                        <form id="formAuthentication" class="mb-3 fv-plugins-bootstrap5 fv-plugins-framework" action="{% url 'messenger:password-reset' %}" method="POST">
                            {% csrf_token %}

                            <input type="hidden" name="reset-email" value="{{ reset_email }}">

                            <div class="mb-3 form-password-toggle fv-plugins-icon-container fv-plugins-bootstrap5-row-valid">
                                <label class="form-label" for="password">New Password</label>

                                <div class="input-group input-group-merge has-validation">
                                    <input type="password" id="password" class="form-control" name="password" placeholder="············" aria-describedby="password">
                                    <span class="input-group-text cursor-pointer"><i class="bx bx-hide"></i></span>
                                </div>
                                
                                <div class="fv-plugins-message-container invalid-feedback"></div>
                            </div>

                            <div class="mb-3 form-password-toggle fv-plugins-icon-container">
                                
                                <label class="form-label" for="confirm-password">Confirm Password</label>
                                
                                <div class="input-group input-group-merge has-validation">
                                    
                                    <input type="password" id="confirm-password" class="form-control" name="confirm-password" placeholder="············" aria-describedby="password">
                                    
                                    <span class="input-group-text cursor-pointer">
                                        <i class="bx bx-hide"></i>
                                    </span>
                                </div>
                                
                                <div class="fv-plugins-message-container invalid-feedback"></div>
                            </div>

                            <button class="btn btn-primary d-grid w-100 mb-3" type="submit">
                                Set new password
                            </button>

                            <div class="text-center">
                                <a href="{% url 'messenger:home' %}">

                                <i class="bx bx-chevron-left scaleX-n1-rtl"></i>

                                Back to login
                                
                                </a>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- /Reset Password -->
            </div>
        </div>
    </div>

{% endblock %}

samples/mariadmin/templates/mariadmin/profile-page.html
{% extends "mariadmin/profile-layout.html" %}

samples/mariadmin/templates/mariadmin/register.html
{% extends "mariadmin/reglog-layout.html" %}

{% block content %}
    <div class="container-xxl">
      
      {% include "mariadmin/alert-toast.html" %}

      <div
        id="login-holder"
        class="authentication-wrapper authentication-basic container-p-y"
      >
        <div class="authentication-inner py-4">
          <!-- Register Card -->
          <div class="card">
            <div class="card-body">
              <!-- Logo -->
              <div class="app-brand justify-content-center">
                <a href="{% url 'messenger:welcome' %}" class="app-brand-link">
                  <span class="app-brand-text demo h3 mb-0 fw-bold"
                    >Mariahill Gardens</span
                  >
                </a>
              </div>

              <!-- /Logo -->
              <p class="mb-4 text-center">
                First 👋 Create an account?
                <i class='bx bxs-hand-down bx-fade-down'></i>
                then make your bookings
              </p>

              <form
                id="formAuthentication"
                class="mb-3"
                action="{% url 'messenger:register' %}"
                method="POST"
              >
                {% csrf_token %}
                <div class="mb-3">
                  <label for="username" class="form-label">Username</label>
                  <input
                    type="text"
                    class="form-control"
                    id="username"
                    name="username"
                    placeholder="Enter your username"
                    autofocus
                  />
                </div>
                <div class="mb-3">
                  <label for="email" class="form-label">Email</label>
                  <input
                    type="text"
                    class="form-control"
                    id="email"
                    name="email"
                    placeholder="Enter your email"
                  />
                </div>
                <div class="mb-3 form-password-toggle">
                  <label class="form-label" for="password">Password</label>
                  <div class="input-group input-group-merge">
                    <input
                      type="password"
                      id="password"
                      class="form-control"
                      name="password"
                      placeholder="&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;&#xb7;"
                      aria-describedby="password"
                    />
                    <span class="input-group-text cursor-pointer"
                      ><i class="bx bx-hide"></i
                    ></span>
                  </div>
                </div>

                <div class="mb-3">
                  <div class="form-check">
                    <input
                      class="form-check-input"
                      type="checkbox"
                      id="terms-conditions"
                      name="terms"
                    />
                    <label class="form-check-label" for="terms-conditions">
                      I agree to
                      <a href="javascript:void(0);">privacy policy & terms</a>
                    </label>
                  </div>
                </div>
                <button class="btn btn-primary w-100">
                  <i class='bx bxs-user-plus bx-burst-hover me-2'></i>
                  Sign up
                </button>
              </form>

              <p class="text-center">
                <span>Already have an account?</span>
                <a href="{% url 'messenger:home' %}">
                  <span>Sign in instead</span>
                </a>
              </p>

              <div class="divider my-4">
                <div class="divider-text">+</div>
              </div>

              <div class="d-flex justify-content-center">
                <span>All rights reserved</span>
              </div>
            </div>
          </div>
          <!-- Register Card -->
        </div>
      </div>
    </div>
{% endblock %}